name: "Continuous Integration"
run-name: Running tests on "${{ github.ref }}" by "${{ github.actor }}"
on: [push, pull_request, workflow_dispatch]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check links with lychee
      uses: lycheeverse/lychee-action@v2.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --root-dir "$(pwd)" --accept '200..=204, 403, 429, 500' --exclude-file '.lycheeignore' --no-progress --timeout 60 --cache --retry-wait-time 3 --max-concurrency 64 README.md
        fail: true
